### ISSUE TITLE
Static Content

### ISSUE THREAD

**Issue by JRJurman** [rit-sse/SpaceJam#3]
![group](https://cloud.githubusercontent.com/assets/326557/13932494/9d793f90-ef7e-11e5-9762-ee440d2eda74.jpg)
![group2](https://cloud.githubusercontent.com/assets/326557/13932495/9d81a464-ef7e-11e5-8cec-97e8f47feaa8.jpg)
![group3](https://cloud.githubusercontent.com/assets/326557/13932496/9d81d7e0-ef7e-11e5-9b73-0512a15c5242.jpg)

**Comment by leeavital** [comment]
:+1:
